from gen.messages_pb2 import ParseLeaderInput
from nodes.parse_leader import parse_leader

# Hand-built per the public MARC21 leader position spec
# (https://www.loc.gov/marc/bibliographic/bdleader.html), not generated by
# pymarc -- expected field values below are computed directly from the
# documented byte positions, independent of the package's own decoder.
#            0123456789012345678901234
KNOWN_LEADER = "01234cam a2200301 a 4500"


def test_parse_leader_matches_hand_computed_positions(ax):
    result = parse_leader(ax, ParseLeaderInput(leader=KNOWN_LEADER))

    assert result.error is False
    assert result.record_length == 1234  # positions 00-04
    assert result.record_status == "c"  # position 05
    assert result.type_of_record == "a"  # position 06
    assert result.bibliographic_level == "m"  # position 07
    assert result.type_of_control == " "  # position 08
    assert result.character_coding_scheme == "a"  # position 09
    assert result.indicator_count == 2  # position 10
    assert result.subfield_code_count == 2  # position 11
    assert result.base_address_of_data == 301  # positions 12-16
    assert result.encoding_level == " "  # position 17
    assert result.descriptive_cataloging_form == "a"  # position 18
    assert result.multipart_resource_record_level == " "  # position 19


def test_parse_leader_wrong_length_returns_structured_error(ax):
    result = parse_leader(ax, ParseLeaderInput(leader="too short"))
    assert result.error is True
    assert "24" in result.error_message


def test_parse_leader_non_numeric_record_length_returns_structured_error(ax):
    bad_leader = "XXXXXcam a2200301 a 4500"
    result = parse_leader(ax, ParseLeaderInput(leader=bad_leader))
    assert result.error is True
    assert "record length" in result.error_message.lower()


def test_parse_leader_non_numeric_base_address_returns_structured_error(ax):
    bad_leader = "01234cam a2XXXXX1 a 4500"
    result = parse_leader(ax, ParseLeaderInput(leader=bad_leader))
    assert result.error is True
    assert "base address" in result.error_message.lower()
